colo evening
set nu
set autoindent
set tabstop=4
set shiftwidth=4

syntax enable
syntax on
colorscheme desert


set tags+=tags


let Tlist_Show_One_File=1
let Tlist_Exit_OnlyWindow=1
let g:winManagerWindowLayout='FileExplorer|TagList'
nmap wm :WMToggle<cr>
let g:winManagerWidth = 30


"new-omni-completion
filetype plugin indent on
set completeopt=longest,menu

"omnicpp
set nocp
filetype plugin on
set completeopt=menu,menuone
let OmniCpp_MayCompleteDot=1  "打开. 操作符
let OmniCpp_MayCompleteArrow=1  "打开 -> 操作符
let OmniCpp_MayCompleteScope=1  "打开 :: 操作符
let OmniCpp_NamespaceSearch=1   "打开命名空间
let OmniCpp_GlobalScopeSearch=1
let OmniCpp_DefaultNamespace=["std"]
let OmniCpp_ShowPrototypeInAbbr=1  "打开显示函数原型
let OmniCpp_SelectFirstItem = 2 "自动弹出时自动跳至第一个
